# Generated by Django 4.2.1 on 2023-08-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Log', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_json', models.JSONField(blank=True, default=list)),
                ('counter', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Log.student')),
            ],
            options={
                'verbose_name_plural': 'Notification Statuses',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('quiz', 'quiz'), ('assingment', 'assignmnet'), ('scheme', 'scheme'), ('timetable', 'timetable')], default='assignment', max_length=100)),
                ('con', models.CharField(max_length=5000)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('link_slug', models.CharField(blank=True, max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.grade')),
            ],
        ),
    ]
