# Generated by Django 4.2.1 on 2023-08-23 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scheme', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('con', models.JSONField(default=list)),
                ('marking_scheme', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('protection', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], default='locked', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheme.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=60, help_text='Duration allowed for Quiz in minutes')),
                ('con', models.JSONField(default=list)),
                ('marking_scheme', models.JSONField(default=list)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheme.scheme')),
            ],
            options={
                'verbose_name_plural': 'quizes',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Quiz.assignment')),
            ],
        ),
    ]
