# Generated by Django 4.2.1 on 2023-08-23 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('min_mark', models.IntegerField()),
                ('max_mark', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('color_code', models.CharField(default='salmon', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(default='default.jpg', upload_to='notice')),
                ('content', models.TextField(max_length=3000)),
                ('published', models.DateField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('grade', models.ManyToManyField(to='Course.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('color', models.CharField(default='salmon', max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('grade', models.ManyToManyField(to='Course.grade')),
            ],
        ),
    ]
